site_name: ndicts documentation

theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
        python:
          docstring_style: "google"

nav:
  - Home: index.md
  - installation.md
  - Usage:
    - quickstart.md
    - initializers.md
  - API reference: reference.md
